train:
  _target_: src.datasets.DigiCamDataset
  split: train
  data_dir: data/digicam
  download_if_missing: false
  save_psf: true
  limit: null

test:
  _target_: src.datasets.DigiCamDataset
  split: test
  data_dir: data/digicam
  download_if_missing: false
  save_psf: true
  limit: null
