train:
  _target_: src.datasets.DigiCamDataset
  split: train
  data_dir: data/digicam
  download_if_missing: false
  save_psf: true
  offset: 0
  limit: 8400
  shuffle_seed: ${seed}

validation:
  _target_: src.datasets.DigiCamDataset
  split: train
  data_dir: data/digicam
  download_if_missing: false
  save_psf: true
  offset: 8400
  limit: 100
  shuffle_seed: ${seed}
