train:
  _target_: src.datasets.DigiCamDataset
  split: train
  data_dir: data/digicam
  download_if_missing: false
  save_psf: true
  offset: 0
  limit: 100

validation:
  _target_: src.datasets.DigiCamDataset
  split: train
  data_dir: data/digicam
  download_if_missing: false
  save_psf: true
  offset: 100
  limit: 100
